In [1]:
import pandas as pd
import numpy as np

In [17]:
#load ontario-2015 csv
df1 = pd.read_csv(r"C:\Users\HP\Downloads\ONTARIO-2015.csv",encoding='ISO-8859-1')
df1

,Date/Time,Year,Month,Day,Data Quality,Max Temp (°C),Max Temp Flag,Min Temp (°C),Min Temp Flag,Mean Temp (°C),...,Total Snow (cm),Total Snow Flag,Total Precip (mm),Total Precip Flag,Snow on Grnd (cm),Snow on Grnd Flag,Dir of Max Gust (10s deg),Dir of Max Gust Flag,Spd of Max Gust (km/h),Spd of Max Gust Flag
0,01-01-2015,2015,1,1,,0.0,NaN,-8.5,NaN,-4.3,...,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN
1,02-01-2015,2015,1,2,,3.0,NaN,-3.0,NaN,0.0,...,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN
2,03-01-2015,2015,1,3,,2.5,NaN,-4.0,NaN,-0.8,...,0.0,NaN,24.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN
3,04-01-2015,2015,1,4,,2.5,NaN,0.0,NaN,1.3,...,1.0,NaN,1.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN
4,05-01-2015,2015,1,5,,-10.0,NaN,-13.5,NaN,-11.8,...,3.0,NaN,3.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360,27-12-2015,2015,12,27,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
361,28-12-2015,2015,12,28,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
362,29-12-2015,2015,12,29,,6.5,NaN,-2.0,NaN,2.3,...,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN
363,30-12-2015,2015,12,30,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
364,31-12-2015,2015,12,31,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
df1.columns

Index(['Date/Time', 'Year', 'Month', 'Day', 'Data Quality', 'Max Temp (°C)',
       'Max Temp Flag', 'Min Temp (°C)', 'Min Temp Flag', 'Mean Temp (°C)',
       'Mean Temp Flag', 'Heat Deg Days (°C)', 'Heat Deg Days Flag',
       'Cool Deg Days (°C)', 'Cool Deg Days Flag', 'Total Rain (mm)',
       'Total Rain Flag', 'Total Snow (cm)', 'Total Snow Flag',
       'Total Precip (mm)', 'Total Precip Flag', 'Snow on Grnd (cm)',
       'Snow on Grnd Flag', 'Dir of Max Gust (10s deg)',
       'Dir of Max Gust Flag', 'Spd of Max Gust (km/h)',
       'Spd of Max Gust Flag'],
      dtype='object')

In [19]:
#load ontario-2016 csv
df2 = pd.read_csv(r"C:\Users\HP\Downloads\ONTARIO-2016.csv",encoding='ISO-8859-1')
df2

,Date/Time,Year,Month,Day,Data Quality,Max Temp (°C),Max Temp Flag,Min Temp (°C),Min Temp Flag,Mean Temp (°C),...,Total Snow (cm),Total Snow Flag,Total Precip (mm),Total Precip Flag,Snow on Grnd (cm),Snow on Grnd Flag,Dir of Max Gust (10s deg),Dir of Max Gust Flag,Spd of Max Gust (km/h),Spd of Max Gust Flag
0,01-01-2016,2016,1,1,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,02-01-2016,2016,1,2,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,03-01-2016,2016,1,3,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,04-01-2016,2016,1,4,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,05-01-2016,2016,1,5,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
361,27-12-2016,2016,12,27,,0.5,NaN,-2.0,NaN,-0.8,...,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN
362,28-12-2016,2016,12,28,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
363,29-12-2016,2016,12,29,,6.0,NaN,-1.5,NaN,2.3,...,0.0,NaN,0.0,NaN,0.0,T,NaN,NaN,NaN,NaN
364,30-12-2016,2016,12,30,,2.5,NaN,-2.5,NaN,0.0,...,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN
365,31-12-2016,2016,12,31,,7.5,NaN,-3.0,NaN,2.3,...,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN

In [21]:
#concat ontario 2015 & 2016
df = pd.concat([df1,df2],ignore_index=True)
df

,Date/Time,Year,Month,Day,Data Quality,Max Temp (°C),Max Temp Flag,Min Temp (°C),Min Temp Flag,Mean Temp (°C),...,Total Snow (cm),Total Snow Flag,Total Precip (mm),Total Precip Flag,Snow on Grnd (cm),Snow on Grnd Flag,Dir of Max Gust (10s deg),Dir of Max Gust Flag,Spd of Max Gust (km/h),Spd of Max Gust Flag
0,01-01-2015,2015,1,1,,0.0,NaN,-8.5,NaN,-4.3,...,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN
1,02-01-2015,2015,1,2,,3.0,NaN,-3.0,NaN,0.0,...,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN
2,03-01-2015,2015,1,3,,2.5,NaN,-4.0,NaN,-0.8,...,0.0,NaN,24.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN
3,04-01-2015,2015,1,4,,2.5,NaN,0.0,NaN,1.3,...,1.0,NaN,1.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN
4,05-01-2015,2015,1,5,,-10.0,NaN,-13.5,NaN,-11.8,...,3.0,NaN,3.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
726,27-12-2016,2016,12,27,,0.5,NaN,-2.0,NaN,-0.8,...,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN
727,28-12-2016,2016,12,28,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
728,29-12-2016,2016,12,29,,6.0,NaN,-1.5,NaN,2.3,...,0.0,NaN,0.0,NaN,0.0,T,NaN,NaN,NaN,NaN
729,30-12-2016,2016,12,30,,2.5,NaN,-2.5,NaN,0.0,...,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN
730,31-12-2016,2016,12,31,,7.5,NaN,-3.0,NaN,2.3,...,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN

In [16]:
#missing values
df.isnull().sum()

Date/Time                      0
Year                           0
Month                          0
Day                            0
Data Quality                 275
Max Temp (°C)                289
Max Temp Flag                717
Min Temp (°C)                322
Min Temp Flag                684
Mean Temp (°C)               322
Mean Temp Flag               684
Heat Deg Days (°C)           322
Heat Deg Days Flag           684
Cool Deg Days (°C)           322
Cool Deg Days Flag           684
Total Rain (mm)              275
Total Rain Flag              721
Total Snow (cm)              275
Total Snow Flag              715
Total Precip (mm)            275
Total Precip Flag            712
Snow on Grnd (cm)            275
Snow on Grnd Flag            723
Dir of Max Gust (10s deg)    731
Dir of Max Gust Flag         731
Spd of Max Gust (km/h)       731
Spd of Max Gust Flag         731
dtype: int64

In [22]:
#remove duplicates
df = df.drop_duplicates()
df.shape

(731, 27)

In [23]:
# these columns have more 700 nan rows so deleting these columns
df = df.drop(columns=['Max Temp Flag','Min Temp Flag','Mean Temp Flag','Heat Deg Days Flag','Cool Deg Days Flag','Total Rain Flag','Total Snow Flag',
        'Total Precip Flag','Snow on Grnd Flag','Dir of Max Gust (10s deg)','Dir of Max Gust Flag','Spd of Max Gust (km/h)','Spd of Max Gust Flag'])

In [20]:
df.columns

Index(['Date/Time', 'Year', 'Month', 'Day', 'Data Quality', 'Max Temp (°C)',
       'Min Temp (°C)', 'Mean Temp (°C)', 'Heat Deg Days (°C)',
       'Cool Deg Days (°C)', 'Total Rain (mm)', 'Total Snow (cm)',
       'Total Precip (mm)', 'Snow on Grnd (cm)'],
      dtype='object')

In [22]:
df.isnull().sum()

Date/Time               0
Year                    0
Month                   0
Day                     0
Data Quality          275
Max Temp (°C)         289
Min Temp (°C)         322
Mean Temp (°C)        322
Heat Deg Days (°C)    322
Cool Deg Days (°C)    322
Total Rain (mm)       275
Total Snow (cm)       275
Total Precip (mm)     275
Snow on Grnd (cm)     275
dtype: int64

In [24]:
# List of columns you want to impute with the mean
columns_to_impute = ['Max Temp (°C)', 'Min Temp (°C)', 'Mean Temp (°C)', 
                     'Heat Deg Days (°C)', 'Cool Deg Days (°C)', 
                     'Total Rain (mm)', 'Total Snow (cm)', 'Total Precip (mm)','Snow on Grnd (cm)']

# Loop through each column and fill missing values with the mean
for col in columns_to_impute:
    df[col].fillna(df[col].mean(), inplace=True)

C:\Users\HP\AppData\Local\Temp\ipykernel_14132\2418161772.py:8: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].mean(), inplace=True)

In [25]:
df.isnull().sum()

Date/Time               0
Year                    0
Month                   0
Day                     0
Data Quality          275
Max Temp (°C)           0
Min Temp (°C)           0
Mean Temp (°C)          0
Heat Deg Days (°C)      0
Cool Deg Days (°C)      0
Total Rain (mm)         0
Total Snow (cm)         0
Total Precip (mm)       0
Snow on Grnd (cm)       0
dtype: int64

In [28]:
df['Data Quality'].value_counts()

Data Quality
    456
Name: count, dtype: int64

In [26]:

# Replace NaN with 'Data Not Recorded' in the 'Data Quality' column
df['Data Quality'] = df['Data Quality'].fillna('Data Not Recorded')

# Replace '' with 'Unverified Data' in the 'Data Quality' column
df['Data Quality'] = df['Data Quality'].replace('', 'Unverified Data')

In [27]:
df.isnull().sum()

Date/Time             0
Year                  0
Month                 0
Day                   0
Data Quality          0
Max Temp (°C)         0
Min Temp (°C)         0
Mean Temp (°C)        0
Heat Deg Days (°C)    0
Cool Deg Days (°C)    0
Total Rain (mm)       0
Total Snow (cm)       0
Total Precip (mm)     0
Snow on Grnd (cm)     0
dtype: int64

In [31]:
df['Data Quality'].value_counts()

Data Quality
Unverified Data      456
Data Not Recorded    275
Name: count, dtype: int64

In [28]:
#datatype
df.dtypes

Date/Time              object
Year                    int64
Month                   int64
Day                     int64
Data Quality           object
Max Temp (°C)         float64
Min Temp (°C)         float64
Mean Temp (°C)        float64
Heat Deg Days (°C)    float64
Cool Deg Days (°C)    float64
Total Rain (mm)       float64
Total Snow (cm)       float64
Total Precip (mm)     float64
Snow on Grnd (cm)     float64
dtype: object

In [29]:
cont_col=cat_col = df.select_dtypes(exclude=['object','datetime64[ns]']).columns
cont_col

Index(['Year', 'Month', 'Day', 'Max Temp (°C)', 'Min Temp (°C)',
       'Mean Temp (°C)', 'Heat Deg Days (°C)', 'Cool Deg Days (°C)',
       'Total Rain (mm)', 'Total Snow (cm)', 'Total Precip (mm)',
       'Snow on Grnd (cm)'],
      dtype='object')

In [30]:
#check outliers
for column in cont_col:

    print(f"Column : {column}")
    iqr = df[column].quantile(0.75) - df[column].quantile(0.25)
    upper_threshold = df[column].quantile(0.75) + (1.5 * iqr)
    lower_threshold = df[column].quantile(0.25) - (1.5 * iqr)
    print(f"UpperThreshold : {upper_threshold} and lowerThreshold : {lower_threshold}")

    print(df[column].describe())
    print('**********************')

Column : Year
UpperThreshold : 2017.5 and lowerThreshold : 2013.5
count     731.000000
mean     2015.500684
std         0.500342
min      2015.000000
25%      2015.000000
50%      2016.000000
75%      2016.000000
max      2016.000000
Name: Year, dtype: float64
**********************
Column : Month
UpperThreshold : 19.0 and lowerThreshold : -5.0
count    731.000000
mean       6.519836
std        3.451913
min        1.000000
25%        4.000000
50%        7.000000
75%       10.000000
max       12.000000
Name: Month, dtype: float64
**********************
Column : Day
UpperThreshold : 45.5 and lowerThreshold : -14.5
count    731.000000
mean      15.738714
std        8.809949
min        1.000000
25%        8.000000
50%       16.000000
75%       23.000000
max       31.000000
Name: Day, dtype: float64
**********************
Column : Max Temp (°C)
UpperThreshold : 33.25 and lowerThreshold : 7.25
count    731.000000
mean      18.350679
std        8.678437
min      -12.000000
25%       17.000000
50%       18.350679
75%       23.500000
max       35.000000
Name: Max Temp (°C), dtype: float64
**********************
Column : Min Temp (°C)
UpperThreshold : 17.380195599022006 and lowerThreshold : 3.033007334963325
count    731.000000
mean       8.413203
std        7.430562
min      -24.000000
25%        8.413203
50%        8.413203
75%       12.000000
max       25.500000
Name: Min Temp (°C), dtype: float64
**********************
Column : Mean Temp (°C)
UpperThreshold : 23.15195599022005 and lowerThreshold : 8.080073349633249
count    731.000000
mean      13.732029
std        7.685442
min      -18.000000
25%       13.732029
50%       13.732029
75%       17.500000
max       30.300000
Name: Mean Temp (°C), dtype: float64
**********************
Column : Heat Deg Days (°C)
UpperThreshold : 15.322127139364309 and lowerThreshold : -8.393276283618585
count    731.000000
mean       6.428851
std        6.188279
min        0.000000
25%        0.500000
50%        6.428851
75%        6.428851
max       36.000000
Name: Heat Deg Days (°C), dtype: float64
**********************
Column : Cool Deg Days (°C)
UpperThreshold : 5.402200488997555 and lowerThreshold : -3.241320293398533
count    731.000000
mean       2.160880
std        2.281358
min        0.000000
25%        0.000000
50%        2.160880
75%        2.160880
max       12.300000
Name: Cool Deg Days (°C), dtype: float64
**********************
Column : Total Rain (mm)
UpperThreshold : 7.3410087719298245 and lowerThreshold : -4.404605263157895
count    731.000000
mean       2.936404
std        5.902493
min        0.000000
25%        0.000000
50%        2.936404
75%        2.936404
max       68.000000
Name: Total Rain (mm), dtype: float64
**********************
Column : Total Snow (cm)
UpperThreshold : 0.6030701754385965 and lowerThreshold : -0.3618421052631579
count    731.000000
mean       0.241228
std        1.075725
min        0.000000
25%        0.000000
50%        0.000000
75%        0.241228
max       15.000000
Name: Total Snow (cm), dtype: float64
**********************
Column : Total Precip (mm)
UpperThreshold : 7.944078947368421 and lowerThreshold : -4.766447368421053
count    731.000000
mean       3.177632
std        5.967757
min        0.000000
25%        0.000000
50%        3.177632
75%        3.177632
max       68.000000
Name: Total Precip (mm), dtype: float64
**********************
Column : Snow on Grnd (cm)
UpperThreshold : 3.0975877192982457 and lowerThreshold : -1.8585526315789473
count    731.000000
mean       1.239035
std        3.768461
min        0.000000
25%        0.000000
50%        0.000000
75%        1.239035
max       30.000000
Name: Snow on Grnd (cm), dtype: float64
**********************

In [32]:
outlier = df[['Max Temp (°C)', 'Min Temp (°C)',
       'Mean Temp (°C)', 'Heat Deg Days (°C)', 'Cool Deg Days (°C)',
       'Total Rain (mm)', 'Total Snow (cm)', 'Total Precip (mm)',
       'Snow on Grnd (cm)']]

In [33]:
#remove outlier
for column in outlier:

    print(f"Column : {column}")

    iqr = df[column].quantile(0.75) - df[column].quantile(0.25)
    upper_threshold = df[column].quantile(0.75) + (1.5 * iqr)
    lower_threshold = df[column].quantile(0.25) - (1.5 * iqr)
    print(f"UpperThreshold : {upper_threshold} and lowerThreshold : {lower_threshold}")

    df[column] = df[column].clip(lower_threshold, upper_threshold)   #cliping- removing outliers
    print(df[column].describe())


    print('**********************')

Column : Max Temp (°C)
UpperThreshold : 33.25 and lowerThreshold : 7.25
count    731.000000
mean      19.087683
std        7.067874
min        7.250000
25%       17.000000
50%       18.350679
75%       23.500000
max       33.250000
Name: Max Temp (°C), dtype: float64
**********************
Column : Min Temp (°C)
UpperThreshold : 17.380195599022006 and lowerThreshold : 3.033007334963325
count    731.000000
mean       9.339485
std        4.486434
min        3.033007
25%        8.413203
50%        8.413203
75%       12.000000
max       17.380196
Name: Min Temp (°C), dtype: float64
**********************
Column : Mean Temp (°C)
UpperThreshold : 23.15195599022005 and lowerThreshold : 8.080073349633249
count    731.000000
mean      14.735270
std        4.721138
min        8.080073
25%       13.732029
50%       13.732029
75%       17.500000
max       23.151956
Name: Mean Temp (°C), dtype: float64
**********************
Column : Heat Deg Days (°C)
UpperThreshold : 15.322127139364309 and lowerThreshold : -8.393276283618585
count    731.000000
mean       5.832702
std        4.616258
min        0.000000
25%        0.500000
50%        6.428851
75%        6.428851
max       15.322127
Name: Heat Deg Days (°C), dtype: float64
**********************
Column : Cool Deg Days (°C)
UpperThreshold : 5.402200488997555 and lowerThreshold : -3.241320293398533
count    731.000000
mean       1.931703
std        1.712661
min        0.000000
25%        0.000000
50%        2.160880
75%        2.160880
max        5.402200
Name: Cool Deg Days (°C), dtype: float64
**********************
Column : Total Rain (mm)
UpperThreshold : 7.3410087719298245 and lowerThreshold : -4.404605263157895
count    731.000000
mean       2.033999
std        2.201128
min        0.000000
25%        0.000000
50%        2.936404
75%        2.936404
max        7.341009
Name: Total Rain (mm), dtype: float64
**********************
Column : Total Snow (cm)
UpperThreshold : 0.6030701754385965 and lowerThreshold : -0.3618421052631579
count    731.000000
mean       0.109724
std        0.146028
min        0.000000
25%        0.000000
50%        0.000000
75%        0.241228
max        0.603070
Name: Total Snow (cm), dtype: float64
**********************
Column : Total Precip (mm)
UpperThreshold : 7.944078947368421 and lowerThreshold : -4.766447368421053
count    731.000000
mean       2.291904
std        2.392401
min        0.000000
25%        0.000000
50%        3.177632
75%        3.177632
max        7.944079
Name: Total Precip (mm), dtype: float64
**********************
Column : Snow on Grnd (cm)
UpperThreshold : 3.0975877192982457 and lowerThreshold : -1.8585526315789473
count    731.000000
mean       0.632083
std        0.826246
min        0.000000
25%        0.000000
50%        0.000000
75%        1.239035
max        3.097588
Name: Snow on Grnd (cm), dtype: float64
**********************

In [34]:
df.to_csv("merged_ontario.csv",index=False) # save the merged dataset